### ISSUE TITLE
Need ICD9 flu-codes or confirmation of ICD10 compatability

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#23]
@alinasmahl1 

We have flu and flu-like codes for ICD10 which work for 2016+ HCUP files.. this logic is captured in the following macros:
- [hcup.dx_flag_flu](https://drexel-uhc.github.io/hcup-dbt/#!/macro/macro.hcup.dx_flag_flu)
- [hcup.dx_flag_flu_like](https://drexel-uhc.github.io/hcup-dbt/#!/macro/macro.hcup.dx_flag_flu_like)

But HCUP was not using ICD10 dx codes but rather ICD9 codes for pre-2015 files (see #22). 

**So questions for you.**
- Will the ICD10 flu/flu-like codes work for ICD9 (e.g. the 2012-2015 files)?
- If not can you provide flu/flu-like codes for ICD9

**Comment by alinasmahl1** [comment]
ah great point- no i don't think that icd-10 will work for icd-9, but I thikn @her43 has code mapping ICD 9 to 10! @her43 is that right?

**Comment by ran-codes** [comment]
sounds good. Will wait on the ICD9 flu  and flu-like codes. No rush we can add that in the next release v0.3

For the release, we present on Wednesday v0.2 we'll just use source tables 2016+ to generate marts. lmk what you think

**Comment by ran-codes** [comment]
great! Going to reassing this issue to @her43 to provide ICD9 flu and flu-like codes.

@her43 lmk if you have any questions and thanks so much for the help!

**Comment by her43** [comment]
icd9 and icd10 codes are extremely different. They can absolutely not be substituted for each other

What I have access to is a crosswalk between GHE (Global health estimates) classifications and general categories of ICD codes, from icd8, icd9, and icd10. Unfortunately, these categories are fairly broad. There is one whole group for all upper respiratory infections, another for lower respiratory infections, etc. 
[data_dictionary.xls](https://github.com/Drexel-UHC/hcup-dbt/files/11193595/data_dictionary.xls)

So, to get specific ICD codes for the flu and flu-like symptoms, we can do some googling instead.

I found this paper that lists 29 ICD9 codes that can be considered flu-like illness.
[Code-based Syndromic Surveillance for Influenzalike Illness by International Classification of Diseases, Ninth Revision](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2725845/) (see table 1)

Also this paper has just the icd9 codes for the flu : [ICD-9 Codes for Identifying Influenza Hospitalizations in Children](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3290931/) "International Classification of Diseases 9th revision (ICD-9) diagnostic codes specific to influenza (487.0, 487.1, and 487.8)"

**Comment by alinasmahl1** [comment]
Thanks @her43 

here's a HCUP article on influenza hopsitalizations https://hcup-us.ahrq.gov/reports/statbriefs/sb253-Influenza-Hospitalizations-ED-Visits-2006-2016.jsp

They list teh following ICD-9 codes 
ICD-9-CM code | Description
-- | --
487.0 | Influenza with pneumonia
487.1 | Influenza with other respiratory manifestations
487.8 | Influenza with other manifestations
488.01 | Influenza due to identified avian flu virus with pneumonia
488.02 | Influenza due to identified avian flu virus with other respiratory manifestations
488.09 | Influenza due to identified avian flu virus with other manifestations
488.11 | Influenza due to identified 2009 H1N1 influenza virus with pneumonia
488.12 | Influenza due to identified 2009 H1N1 influenza virus with other respiratory manifestations
488.19 | Influenza due to identified 2009 H1N1 influenza virus with other manifestations
488.81 | Influenza due to identified novel influenza A virus with pneumonia
488.82 | Influenza due to identified novel influenza A virus with other respiratory manifestations
488.89 | Influenza due to identified novel influenza A virus with other manifestations

**Comment by her43** [comment]
> 488.01	Influenza due to identified avian flu virus with pneumonia
> 488.02	Influenza due to identified avian flu virus with other respiratory manifestations
> 488.09	Influenza due to identified avian flu virus with other manifestations
> 488.11	Influenza due to identified 2009 H1N1 influenza virus with pneumonia
> 488.12	Influenza due to identified 2009 H1N1 influenza virus with other respiratory manifestations
> 488.19	Influenza due to identified 2009 H1N1 influenza virus with other manifestations
> 488.81	Influenza due to identified novel influenza A virus with pneumonia
> 488.82	Influenza due to identified novel influenza A virus with other respiratory manifestations
> 488.89	Influenza due to identified novel influenza A virus with other manifestations

I should note that the tenths place in the decimal is the category for the illness, and the hundredths place in the decimal is simply a subcategory. So for example, X.1 includes all of X.11, X.12, X.13, etc. So all influenza-specific codes are included in 488.0, 488.1, and 488.8. But it's good that we know these additional subcategories (488.01, etc.) exist because they might also exist in the HCUP data, and filtering for only codes with one decimal place would exclude cases.

So @ran-codes if you do a filter of some sort to look for the icd9 codes for the flu (or any illness), make sure to search for the **pattern** of the one-decimal-place-code (e.g., `pattern = "488.0"`, etc.). Or round the values to one decimal place, if they are numeric. Rather than, say searching for an exact match (`value == "488.0"`).

**Comment by her43** [comment]
I realized my comment I made a couple minutes ago was incorrect, so I deleted it.

**Comment by alinasmahl1** [comment]
@her43 let's tlak next steps on this. i think it's including a macro for the groupings and then adding code to ID flu and ILI for ICD-9

**Comment by alinasmahl1** [comment]
@her43 @her43 re-pinging this to discuss tomorrow. we need to make sure we're pulling in the ICD-9 codes to the IP marts for any years that include ICD-9 (that includes 1/2 of 2015 and before) and then figuring out to ID influenza hospitalizations.

**Comment by her43** [comment]
yes, I added the ICD-9 Flu and ILI codes to the sql code.

In **hcup-dbt/macros/dx_recoding/flu/dx_flag_flu.sql**

```
{%- macro dx_flag_flu(db) -%}
 
    {% set flu_codes_icd9 = ('4870', '4871', '4878', '48801', '48802', '48809', '48811', '48812', '48819', '48881', '48882', '48889')   %}
    {% set flu_codes_icd10 = ('J1000', 'J1001', 'J1008', 'J101', 'J102', 'J1081', 'J1082', 'J1083', 'J1089', 'J1100', 'J1108', 'J111', 'J112', 'J1181', 'J1182', 'J1183', 'J1189', 'J09X1', 'J09X2', 'J09X3', 'J09X9')   %}

    {% if db == "SID" %}
        I10_DX1 IN {{flu_codes_icd10}} OR 
        I10_DX2 IN {{flu_codes_icd10}} OR
        DX1 IN {{flu_codes_icd9}} OR 
        DX2 IN {{flu_codes_icd9}}
    {% else %}
        I10_DX_Visit_Reason1 IN {{flu_codes_icd10}} OR 
        I10_DX_Visit_Reason2 IN {{flu_codes_icd10}} OR 
        I10_DX1 IN {{flu_codes_icd10}} OR 
        I10_DX2 IN {{flu_codes_icd10}} OR
        DX1 IN {{flu_codes_icd9}} OR 
        DX2 IN {{flu_codes_icd9}}
    {% endif %}

{%- endmacro -%}
```

and in **hcup-dbt/macros/dx_recoding/flu/dx_flag_flu_like.sql**

```
{%- macro dx_flag_flu_like(db) -%}
 
    {% set flu_like_codes_icd9 = ('07989', '07999', '460', '462', '46400', '46410', '46420', '4650', '4658', '4659', '4660', '46611', '46619', '4789', '4800', '4801', '4802', '4808', '4809', '4848', '485', '486', '4870', '4871', '4878', '490', '7806', '7841', '7862')   %}
    {% set flu_like_codes_icd10 = ('J069', 'J399', 'J200', 'J201', 'J202', 'J203', 'J204', 'J205', 'J206', 'J207', 'J208', 'J209', 'J210', 'J211', 'J218', 'J219', 'J40', 'B012', 'B052', 'B0681', 'B250', 'J120', 'J121', 'J122', 'J123', 'J1281', 'J1289', 'J129', 'J440', 'J441', 'J470', 'J471')   %}
    
    {% if db == "SID" %}
        I10_DX1 IN {{flu_like_codes_icd10}} OR 
        I10_DX2 IN {{flu_like_codes_icd10}} OR 
        DX1 IN {{flu_like_codes_icd9}} OR 
        DX2 IN {{flu_like_codes_icd9}}
    {% else %}
        I10_DX_Visit_Reason1 IN {{flu_like_codes_icd10}} OR 
        I10_DX_Visit_Reason2 IN {{flu_like_codes_icd10}} OR 
        I10_DX1 IN {{flu_like_codes_icd10}} OR 
        I10_DX2 IN {{flu_like_codes_icd10}} OR 
        DX1 IN {{flu_like_codes_icd9}} OR 
        DX2 IN {{flu_like_codes_icd9}}
    {% endif %}


{%- endmacro -%}
```

And added to **hcup-dbt/models/intermediate/flu/int__flu_ip.sql** in this chunk of code:

```
cte_1 as (
  SELECT 
    {{dx_flag_flu(db="SID")}} AS flu,
    {{dx_flag_flu_like(db="SID")}} AS flu_like, 
    CASE
      WHEN (flu AND flu_like) THEN 'BOTH'
      WHEN (flu AND NOT(flu_like)) THEN 'ILI'
      WHEN (NOT(flu) AND flu_like) THEN 'ILI LIKE'
      ELSE 'OTHER'
      END AS ili_diagnosis_var, 
    CASE WHEN LENGTH(ZIP) = 5 THEN ZIP ELSE NULL END AS ZIP,
    *
    
  FROM {{ref('int__sid_core')}}
),
```

I think the remaining question here is are there other remaining ICD variables (e.g., more DX variables) to check for the flu & ILI ICD codes? 

And I don't think I changed the SEDD/ER flu SQL code (int__sedd_core.sql and int__flu_er.sql)

**Comment by ran-codes** [comment]
Original issue was clarification on what Codes. That is done. 

Opening new issues to address the depth of DX code search for flu macro (2 vs 10 or have an argument)  #41
