### ISSUE TITLE
Add Alina's Computer to run dbt

### ISSUE THREAD

**Issue by alinasmahl1** [Drexel-UHC/hcup-dbt#31]
add Alina's Computer to run HCUP DBT

## Action Items

- [x] @alinasmahl1  to email Ran and Heather Alina's work desktop IP address
- [x] @ran-codes and @her43 to set up GitHub, DBT on 7/10 1:1

**Comment by ran-codes** [comment]
@alinasmahl1  added some action above. TO find you IP address you can just google 'what is my IP address' (see snip below). 

![Image](https://github.com/Drexel-UHC/hcup-dbt/assets/45013044/60095ff5-b175-4a58-a1c4-001900f5f19a)

**Comment by alinasmahl1** [comment]
@ran-codes IP address is 68.82.169.158

**Comment by usamabilal** [comment]
For whatever’s worth, my IP has a very different structure. I wonder if that’s the public IP instead of the internal Drexel one. I think I got mine by doing ipconfig in the command line

From: alinasmahl1 ***@***.***>
Date: Monday, July 10, 2023 at 10:27 AM
To: Drexel-UHC/hcup-dbt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Drexel-UHC/hcup-dbt] Add Alina's Computer to run dbt (Issue #31)

External.

@ran-codes<https://github.com/ran-codes> IP address is 68.82.169.158

**Comment by alinasmahl1** [comment]
Ah i think you're right, thanks-- here it is from running ipconfig  

Connection-specific DNS Suffix  . : dhcp.drexel.edu
   Link-local IPv6 Address . . . . . : fe80::2e89:3e0c:13c6:fdb9%8
   IPv4 Address. . . . . . . . . . . : 10.248.120.217
   Subnet Mask . . . . . . . . . . . : 255.255.252.0
   Default Gateway . . . . . . . . . : 10.248.123.254

**Comment by usamabilal** [comment]
Yep, the 10.248.120.217 one looks very similar to mine, whichi makes sense in this context. Since you can only connect to the RDP with the VPN, it makes sense that it’s the internal address that matters.

From: alinasmahl1 ***@***.***>
Date: Monday, July 10, 2023 at 10:47 AM
To: Drexel-UHC/hcup-dbt ***@***.***>
Cc: Bilal,Usama ***@***.***>, Comment ***@***.***>
Subject: Re: [Drexel-UHC/hcup-dbt] Add Alina's Computer to run dbt (Issue #31)

External.

Ah i think you're right, thanks-- here it is from running ipconfig

Connection-specific DNS Suffix . : dhcp.drexel.edu
Link-local IPv6 Address . . . . . : fe80::2e89:3e0c:13c6:fdb9%8
IPv4 Address. . . . . . . . . . . : 10.248.120.217
Subnet Mask . . . . . . . . . . . : 255.255.252.0
Default Gateway . . . . . . . . . : 10.248.123.254

**Comment by her43** [comment]
both @ran-codes and I tried to remote connect to Alina's computer and it didn't work.

**Comment by ran-codes** [comment]
![image](https://github.com/Drexel-UHC/hcup-dbt/assets/45013044/7bde527c-6c42-40a8-8db8-4236fca037f9)

**Comment by her43** [comment]
I get this error message: 
![image](https://github.com/Drexel-UHC/hcup-dbt/assets/77505955/86c037f8-f667-4a0c-8009-e8df4aa92693)

**Comment by alinasmahl1** [comment]
wondering if it was maybe turned off ? It is definitely authorized for remote log in, since I remotely log in regularly. I'll be in office tomorrow and can investigate further

**Comment by ran-codes** [comment]
@alinasmahl1 just checking so your still able to remote connect right? (just others cannot connect?)

**Comment by alinasmahl1** [comment]
@ran-codes yup, i can still remote connect

**Comment by her43** [comment]
This issue is handled. Alina's and Usama's computers both have 64 GB RAM. Heather has accessed both computers successfully. closing.
